app1/urls.py
from django.urls import path
from app1.views import *
app_name='divyac'

urlpatterns=[
    path('divya/',divya,name='divya'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='charanc'

urlpatterns=[
    path('charan/',charan,name='charan')
]

project7/urls.py
from django.contrib import admin
from django.urls import path,include
from app.views import *
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',login,name='login'),
    path('reg/',reg,name='reg'),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def login(request):
    return render(request,'login.html')
def reg(request):
    return render(request,'reg.html')

app1/views.py
from django.shortcuts import render

# Create your views here.
def divya(request):
    return render(request,'divya.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def charan(request):
    return render(request,'charan.html')

templates/charan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
    <h1>charan speaking  to divya</h1>
    <h1>enti akka</h1>
    <h1>vasthunaaa......</h1>
    <a href="{% url 'divyac:divya' %}"><h1>divya response</h1></a>
    </center>
</body>
</html>

templates/divya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
    <h1>divya speaking to charan</h1>
    <h1>rey emii chesthunavu raa amma pellusthudhii tvaraga raa</h1>
    <a href="{% url 'charanc:charan' %}"><h1>charan response</h1></a>
    </center>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="color:aliceblue">
    <nav style="background-color: black;">
        <h1>login page</h1>
        
    </nav>
    <div>
        <span>
            <a href="{% url 'reg'   %}">register</a>
        </span>
            <input type="text" placeholder="enter your name">
            <input type="password" placeholder="enter password">
            <button>submit</button>
    </div>
</body>
</html>

templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="color:aliceblue">
    <nav style="background-color: black;">
        <h1>login page</h1>
        
    </nav>
    <div>
        <span>
            <a href="{%  url  'login' %}">login</a>
        </span>
            <input type="text" placeholder="enter your name">
            <input type="password" placeholder="enter password">
            <button>submit</button>
    </div>
</body>
</html>